radius: 10
max-length: 10
min-length: 3
titles:
- lowest: 2
#  sound:
#    id: "entity.arrow.hit_player"
#    volume: 100.0
#    pitch: 1.0
  title: "&4%number%"
# subtitle: "subtitle"
- lowest: 1
  title: "&e%number%"
# subtitle: "subtitle"
- lowest: 0
  title: "&2Los!"
# subtitle: "subtitle"
msg:
  started: "&eCountdown wurde gestartet (%time% Sek.)"
  finished: "&a%time% Sekunden Countdown erfolgreich beendet."
  cancelled: "&eCountdown abgebrochen!"
  error:
    syntax: "&c/counter <zeit>|cancel <startername>|reload"
    no-permission: "&cDu hast nicht das Recht %permission%!"
    not-a-number: "&c%input% ist keine Nummer!"
    countdown-too-long: "&c%input% ist zu lang! Die maximale Länge ist %max-length% Sekunden!"
    countdown-too-short: "&c%input% ist zu kurz! Die minimale Länge ist %min-length% Sekunden!"
    no-countdown-running: "&cEs läuft zur Zeit kein Countdown?"
    countdown-already-running: "&cEs läuft zur Zeit schon ein Countdown! Beende ihn mit /counter cancel."
    unsupported-sender: "&c%type% können keine Countdowns starten!"