name: ${project.name}
version: '${minecraft.plugin.version}'
main: de.redstoneworld.redcountdown.RedCountdown
authors: [Phoenix616]
commands:
   redcountdown:
      aliases: [counter,countdown]
      description: Plugin command description.
      usage: /<command> <time>|cancel <startername>|reload
      permission: rwm.redcountdown.use
      permission-message: You don't have the permission <permission>
permissions:
   rwm.redcountdown.use:
      description: Gives permission to the plugin command
      default: op
   rwm.redcountdown.reload:
      description: Gives permission to reload the plugin
      default: op
   rwm.redcountdown.cancel.others:
      description: Gives permission to cancel countdowns started by others
      default: op